### ISSUE TITLE
feature req: add man page

### ISSUE THREAD

**Issue by sewnie** [leath-dub/sscreenshot#1]
makes my life alot easier since i am used to reading man pages.

also took me a very long time to figure out that its not instant screenshot and its mouse 2 to leave

**Comment by leath-dub** [comment]
yeah there is no reason I shouldn't add a man page, I will work on that asap, thanks for feedback

**Comment by leath-dub** [comment]
Just added a manual page ``sss.1``, also edited the Makefile to copy it to the manual path. I think its safe to close this issue.
